name: dsa4265
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pypdf2  
  - ipykernel
  - git-lfs    
  - setuptools=57.4.0
  - openssl=1.1.1
  - ipython
  - transformers==4.50.0
  - tokenizers
  - fuzzywuzzy
  - pdftotext
  - pip
  - pip:
    - psycopg2
    - httpx
    - aiohttp==3.10.8
    - PyMuPDF    
    - pandas==2.2.3
    - requests==2.32.3 
    - nltk==3.9.1 
    - pyyaml==6.0.2
    - pydantic==2.9.2
    - pydantic-core==2.23.4
    - pydantic-settings==2.5.2
    - typing_extensions==4.11.0
    - urllib3==2.2.3
    - python-dotenv==1.0.1
    - openai==1.70.0
    - langchain==0.3.1
    - langchain-community==0.3.1
    - langchain-core==0.3.6
    - langchain-openai==0.2.0
    - langchain-text-splitters==0.3.0
    - pillow==11.1.0
    - seaborn==0.13.2
    - plotly==5.24.1
    - bertopic==0.16.3
    - beautifulsoup4==4.12.3
    - matplotlib==3.9.2
    - scikit-learn==1.5.2
    - scipy==1.13.1
    - tqdm==4.66.5
    - ipywidgets
    - kagglehub
    - torch==2.2.2
    - numpy
    - scikit-learn
    - selenium
    - accelerate>=0.26.0
    - pinecone==6.0.2
    - py2neo==2021.2.4
    - pinecone-plugin-interface==0.0.7
    - neo4j==5.28.1
    - neo4j-graphrag==1.6.1
    - networkx==3.2.1
    - flask 