name: proj_DSA4265
channels:
  - conda-forge
  - defaults
dependencies:
## need to install pngquant manually
## for windows pip install ocrmypdf
## for cuda gpu runtimes pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu126
  - python=3.9
  - pypdf2  
  - ipykernel
  - git-lfs    
  - spacy
  - setuptools=57.4.0
  - openssl=1.1.1
  - ipython
  - transformers
  - tokenizers
  - fuzzywuzzy
  - pdftotext
  - pytorch
  - cudatoolkit=11.8
  - pip
  - pip:
    - psycopg2
    - googlesearch-python
    - httpx
    - aiohttp==3.10.8
    - google-generativeai
    - PyMuPDF     
    - chromadb
    - pandas==2.2.3
    - requests==2.32.3 
    - nltk==3.9.1 
    - pyyaml==6.0.2
    - pydantic==2.9.2
    - pydantic-core==2.23.4
    - pydantic-settings==2.5.2
    - typing_extensions==4.11.0
    - urllib3==2.2.3
    - python-dotenv==1.0.1
    - openai==1.51.0
    - langchain==0.3.1
    - langchain-community==0.3.1
    - langchain-core==0.3.6
    - langchain-openai==0.2.0
    - langchain-text-splitters==0.3.0
    - pillow==10.4.0
    - seaborn==0.13.2
    - plotly==5.24.1
    - bertopic==0.16.3
    - beautifulsoup4==4.12.3
    - matplotlib==3.9.2
    - pio==0.0.3 
    - scikit-learn==1.5.2
    - scipy==1.13.1
    - tqdm==4.66.5
    - torch==2.4.1
    - ipywidgets
    - kagglehub
    - torch 
    - numpy
    - scikit-learn
    - selenium
    - accelerate>=0.26.0
    - pinecone-client
    - py2neo
    